### ISSUE TITLE
你好，可否分享html_ori文件夾下所有HTML文件的源電子書？

### ISSUE THREAD

**Issue by V4n1sh** [robertsjchen/JPM_Congzhen#1]
你好，可否分享html_ori文件夾下所有HTML文件的源電子書，即應爲epub或者mobi後綴的電子書文件。非常想要，萬分感謝。

**Comment by robertsjchen** [comment]
[
[《新刻繡像批評金瓶梅》（繁體直排精校）.epub.zip](https://github.com/robertsjchen/JPM_Congzhen/files/6022686/epub.zip)
](url) 您好，上传原始附件文件，把后缀zip去掉就行。这份档案是来自百度贴吧的最初分享，其中不少错误内容，如果希望修改后的epub电子档的话，您可以从本代码仓库下载html_ori目录下最新html文件，用任何压缩工具打开epub文件替换相应内容即可。

**Comment by V4n1sh** [comment]
已收閲，十分感謝
